version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - 80:8080
      - 50003:50000
    container_name: jenkins-server
    restart: always
    volumes:
      - /.jenkins:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock